name: CI/CD-pipeline-AWS-ElasticBeanstalk
env:
  EB_PACKAGE_S3_BUCKET_NAME: "mdv-unre-flask-application-packages"
  EB_APPLICATION_NAME      : "my-flask"
  EB_ENVIRONMENT_NAME      : "MyFlask-env"
  DEPLOY_PACKAGE_NAME      : "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME          : "eu-central-1"
on:
  push:
    branches: [ master ]
jobs:
  My-CI-part:
    runs-on: ubuntu-latest
    steps:
      - name: "Git clone my repo "
        uses: actions/checkout@v2

      - name: "CreateZIP Deployment Package"
        run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x *.git*
        
      - name: "Configure AWS credentials"
        uses:  aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_GITUSER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GITUSER_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
      
      - name: "Copy Deployment package to AWS s3 bucket"
        run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}
        
      - name: "Print Message for CI-part finish"
        run : echo "CI-part finished successfully" 
  My-CD-part:
    runs-on: ubuntu-latest
    needs: [My-CI-part]
    steps:
      - name:  "Configure AWS credentials"
        uses:  aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id    : ${{ secrets.AWS_GITUSER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_GITUSER_SECRET_KEY }}
          aws-region           : ${{ env.AWS_REGION_NAME }}
      
      - name: "Create new Elastic BeanStalk Application Version"
        run : |
          aws elasticbeanstalk create-application-version \
          -- application-name ${{ env.EB_APPLICATION_NAME }} \
          -- source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ DEPLOY_PACKAGE_NAME }}" \
          -- version-label "Ver-${{ github.sha }}" \
          -- description "Commit SHA-${{ github.sha }}"
      
      - name: "Deploy new Elastic BeanStalk Application Version"
        run : aws elasticbeanstalk update-environment --environment-name "${{ env.EB_ENVIRONMENT_NAME }}" --version-label "Ver-${{ github.sha }}"      
                        
      - name: "Print Message for CD-part finish"
        run : echo "CD-part finished successfully"
       
       
       
       
       
       
