name: Pull-request-test
env:
  WORKDIR_PATH: "cat pwd.txt" 
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "upload"      
        uses: actions/checkout@v2
      - name: "run few commands"  
        run: |
          pwd | tee pwd.txt
      - name: "Check index file"
        run : cat ${{ env.WORKDIR_PATH }}/templates/index.html    
              

     
